[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
priority=1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:queue]
command=php artisan queue:work --tries=3 --timeout=90
directory=/var/www/html
priority=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr