name: Deploy Delivery App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 164.68.109.98
          port: 22
          username: deploy
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/delivery/delivery-deployment
            bash scripts/deploy.sh